#Вказування версії синтаксису Docker Compose На даний момент остання версія 3
version: "3"
#Переліе сервісів для виконання
services:
  #Вказуємо ім'я сервісу
  nginx:
    #Вказуємо образ, яий необхідно використовувати для створення контейнеру. Використовуємо останній образ Nginx
    image: nginx:latest
    #Вказуємо маппінг портів між контейнером і хостом
    ports:
      - "80:80"
      - "446:443"
    #Визначаємо зв'язок між локальними та контейнерними директоріями. У цьому випадку директорія /var/www/ контейнеру пов'язана з /tmp на локальній машині
    volumes:
      - /var/www/:/tmp/
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    #Вказуємо умови перезапуску контейнеру. У даному випадку перезапуск відбудеться при виявлені помилки
    restart: on-failure
