apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: user-api
    image: registry.gitlab.com/dev-ops-dosvit/microservice-app/users-api:latest
  imagePullSecrets:
  - name: gitlab-token-auth
